### ISSUE TITLE
Ball speed increase w/o resetting @ gameStart

### ISSUE THREAD

**Issue by maherhalabi** [mohur/rally#2]
Ball increases speed with every paddle hit but, continues after game reset.
https://github.com/mohur/rally/blob/ff9314d29f040b932944c9f1537f1990d2e7c914/index.js#L41-L50

**Comment by Noitidart** [comment]
Taking a look now.

**Comment by Noitidart** [comment]
Fixed and submitted PR #3 - needs your review and approval - which will then merge to your branch. Understand the fix I made before merging it though. It was a funny fix.
